version: "3"

networks:
  default:
    external:
      name: external

services:
  ethereum_mainnet:
    image: ethereum/client-go
    container_name: ethereum_mainnet
    hostname: ethereum_mainnet
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8585:8585" # websocket
      - "8546:8546"
      - "6060:6060"
    volumes:
      - ./data/goethereum:/var/lib/goethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --nousb
      - --http
      - --syncmode
      - full
      - --gcmode
      - archive        
      - --nousb
      - --cache
      - "8192"
      - --maxpeers
      - "100"
      - --metrics
      - --pprof
      - --pprof.addr=0.0.0.0
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain="*"
      - --ws
      - --ws.port=8585
      - --ws.origins="*"
      - --ws.addr=0.0.0.0
      - --ws.api
      - "eth,net,web3"
      - --datadir
      - "/var/lib/goethereum"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  ethereum_kovan:
    image: parity/parity:latest
    container_name: ethereum_kovan
    hostname: ethereum_kovan
    restart: unless-stopped
    user: parity:parity
    ports:
      - "30304:30303"
      - "30303:30303/udp"
      - "38548:8546"
      - "38547:8545"
    volumes:
      - ./data/kovan:/data/kovan/
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --chain
      - kovan
      - --mode 
      - active
      - --port 
      - "30303"
      - --base-path 
      - /tmp/kovan/
      - --jsonrpc-port 
      - "8545"
      - --jsonrpc-interface 
      - "all" 
      - --jsonrpc-cors 
      - "all"
      - --jsonrpc-hosts 
      - "all" 
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"  